### ISSUE TITLE
NOPersistentStore not working properly with Class Arrays and subscripting.

### ISSUE THREAD

**Issue by PPacie** [nodes-ios/Cashier#24]
Hi Guys,

How are you doing? It’s been so much time =) 

I am having troubles with `NOPersistentStore` and final Class Arrays objects.

For example: If I cache an array of a Final Class type and then I update one of its elements by subscripting e.g: `myCars[indexPath.row].isNew = true` it will update the cache but the next time I open the app the cache will go back to previous status.

It doesn’t happen if `Car` is a Value Type (struct, enum, etc) instead of a `NSObject`.

And it also doesn’t happen if the array item is replaced entirely. For example: `myCar[indexPath.row] = Car()` works fine when reopening the app.

PS: Attached you will find the data structure example, just in case it's needed.
[dataExample.zip](https://github.com/nodes-ios/Cashier/files/1075603/dataExample.zip)

Thanks in advance. Say hi to all the team!

**Comment by dominik-hadl** [comment]
@PPacie Hey Pablo! 

Long time no sea 🏄  (sorry for the lame pun)

I think the issue is actually not in Cashier but in the way you use it. The reason why structs work is because when you set one of their properties, they are copied and set again using the subscript, so the value in the cache is updated.

While with classes it only has a reference to the object in a memory, so it just changes the value directly instead of copying it and setting it again. The reason why this still works when you stay in the app is because Cashier also keeps a memory cache for objects you access, and it will get updated in that one because you are accessing the object directly - however the subscript in Cashier will never get called as it thinks nothing has changed.

Hopefully that makes more sense? 

So to fix this you'd need to keep a reference to the class you get from the cache, set your new value and then save it back to the cache.

All of the team says hi 👋

**Comment by PPacie** [comment]
Hey Dom, thanks for the quick reply.

Yes, I was doing exactly what you suggested to get new values cached but it felt a bit weird by the fact that it worked by subscripting until the app was closed. So, I thought that there could be some issues with NOPersistentStore. 

Anyway, thanks for the explanation =)
